default:
  db_name: "scagent"
  db_host: "10.28.1.24"
  db_port: 5432
  db_user: "yanglab"
  db_password: "" 
  db_timeout: 60
  service_tier: "standard"
  flex_timeout: 180
test:
  db_name: "scagent"
  models:
    default: "Qwen3-235B-A22B"
    esearch: "Qwen3-235B-A22B"
    esummary: "Qwen3-235B-A22B"
    elink: "Qwen3-235B-A22B"
    efetch: "Qwen3-235B-A22B"
    sequences: "Qwen3-235B-A22B"
    ncbi_fetch: "Qwen3-235B-A22B"
    bigquery: "Qwen3-235B-A22B"
    entrez: "Qwen3-235B-A22B"
    sragent: "Qwen3-235B-A22B"
    tissue_ontology: "Qwen3-235B-A22B"
    metadata: "Qwen3-235B-A22B"
    metadata_router: "Qwen3-235B-A22B"
    convert_router: "Qwen3-235B-A22B"
    accessions: "Qwen3-235B-A22B"
    entrez_convert: "Qwen3-235B-A22B"
    find_datasets: "Qwen3-235B-A22B"
    step_summary: "Qwen3-235B-A22B"
    get_entrez_ids: "Qwen3-235B-A22B"
  temperature:
    default: 0.1
    esearch: 0.1
    esummary: 0.1
    elink: 0.1
    efetch: 0.1
    sequences: 0.1
    ncbi_fetch: 0.1
    bigquery: 0.1
    entrez: 0.1
    sragent: 0.1
    tissue_ontology: 0.1
    metadata: 0.1
    convert_router: 0.1
    metadata_router: 0.1
    accessions: 0.1
    entrez_convert: 0.1
    find_datasets: 0.1
    step_summary: 0.1
    get_entrez_ids: 0.0
  reasoning_effort:
    default: "low"
    esearch: "low"
    esummary: "low"
    elink: "low"
    efetch: "low"
    sequences: "low"
    ncbi_fetch: "low"
    bigquery: "low"
    entrez: "low"
    sragent: "medium"
    tissue_ontology: "medium"
    metadata: "medium"
    convert_router: "low"
    metadata_router: "medium"
    accessions: "low"
    entrez_convert: "low"
    find_datasets: "low"
    step_summary: ""
    get_entrez_ids: "low"
  max_tokens:
    default: 4096
    find_datasets: 4096
  service_tier:
    default: "default"
    esearch: "default"
    esummary: "default"
    elink: "default"
    efetch: "default"
    sequences: "default"
    ncbi_fetch: "default"
    bigquery: "default"
    entrez: "default"
    sragent: "default"
    tissue_ontology: "default"
    metadata: "default"
    metadata_router: "default"
    convert_router: "default"
    accessions: "default"
    entrez_convert: "default"
    find_datasets: "default"
    step_summary: "default"
    get_entrez_ids: "default"
    
prod:
  db_name: "scagent"
  models:
    default: "Qwen3-235B-A22B"
    esearch: "Qwen3-235B-A22B"
    esummary: "Qwen3-235B-A22B"
    elink: "Qwen3-235B-A22B"
    efetch: "Qwen3-235B-A22B"
    sequences: "Qwen3-235B-A22B"
    ncbi_fetch: "Qwen3-235B-A22B"
    bigquery: "Qwen3-235B-A22B"
    entrez: "Qwen3-235B-A22B"
    sragent: "Qwen3-235B-A22B"
    tissue_ontology: "Qwen3-235B-A22B"
    metadata: "Qwen3-235B-A22B"
    metadata_router: "Qwen3-235B-A22B"
    convert_router: "Qwen3-235B-A22B"
    accessions: "Qwen3-235B-A22B"
    entrez_convert: "Qwen3-235B-A22B"
    find_datasets: "Qwen3-235B-A22B"
    step_summary: "Qwen3-235B-A22B"
    get_entrez_ids: "Qwen3-235B-A22B"
  temperature:
    default: 0.1
    esearch: 0.1
    esummary: 0.1
    elink: 0.1
    efetch: 0.1
    sequences: 0.1
    ncbi_fetch: 0.1
    bigquery: 0.1
    entrez: 0.1
    sragent: 0.1
    tissue_ontology: 0.1
    metadata: 0.1
    convert_router: 0.1
    metadata_router: 0.1
    accessions: 0.1
    entrez_convert: 0.1
    find_datasets: 0.1
    step_summary: 0.1
    get_entrez_ids: 0.0
  reasoning_effort:
    default: "low"
    esearch: "low"
    esummary: "low"
    elink: "low"
    efetch: "low"
    sequences: "low"
    ncbi_fetch: "low"
    bigquery: "low"
    entrez: "low"
    sragent: "medium"
    tissue_ontology: "medium"
    metadata: "medium"
    convert_router: "low"
    metadata_router: "medium"
    accessions: "low"
    entrez_convert: "low"
    find_datasets: "low"
    step_summary: "medium"
    get_entrez_ids: "low"
  service_tier:
    default: "default"
    esearch: "default"
    esummary: "default"
    elink: "default"
    efetch: "default"
    sequences: "default"
    ncbi_fetch: "default"
    bigquery: "default"
    entrez: "default"
    sragent: "default"
    tissue_ontology: "default"
    metadata: "default"
    metadata_router: "default"
    convert_router: "default"
    accessions: "default"
    entrez_convert: "default"
    find_datasets: "default"
    step_summary: "default"
    get_entrez_ids: "default"
  
claude:
  db_name: "scagent"
  models:
    default: "Qwen3-235B-A22B"
  temperature:
    default: 0.1
  reasoning_effort:
    esearch: "low"
    efetch: "low"
    sequences: "low"
    ncbi_fetch: "low"
    bigquery: "medium"
    entrez: "medium"
    sragent: "medium"
    tissue_ontology: ""
    metadata: "high"
    metadata_router: "medium"
    accessions: "low"
    entrez_convert: "medium"
    find_datasets: "medium"
    step_summary: ""
  qwen_api_base: "http://10.28.1.21:30080/v1"
  qwen_api_key: ""
  service_tier:
    default: "default"